version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - PORT=5001
      # Add more if needed (e.g., OPENAI_API_KEY or LanguageTool URL)
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Expose React frontend via Nginx
    depends_on:
      - server
    restart: always
